language: java
jdk:
  - oraclejdk8
os:
  - linux
  #- osx # jdk section not supported on OS X
env:
  global:
    # COVERITY_SCAN_TOKEN (https://docs.travis-ci.com/user/encryption-keys/)
    - secure: "In3/FzSdMz+o5Tqho05dXGFeqeb/XWo0D0rdhKZ5acp6D/lxjTw8Xo/tMZQb9Ur50XDMn4SdjyGnfkiYRar13g51+xlOnY+4MUqtRzvfuLyohtOMN8PrmQbNWVneuq3I/Xn+fcDWsZavqmUGB7hac5h6Uip4qq8YnbFy5Gn6v6I="
    # VERSIONEYE_API_KEY (https://docs.travis-ci.com/user/encryption-keys/)
    - secure: "PmoYZFRSXqRirNcOm+NSBzfgAntUtJ/1OiDz7nTJBOpZ1mS8Oay6wIO43J8DJ3fAhGQtNb8453jpecPpLnu+IpVGv4UOnAVgcxHodgl9WwggLWTCwxwWp+LhRXnxkWeIyOoIE2S44vR0w89PK+kjJMg/nUaKfVQ07Hz8uXgUOtU="
    # SONATYPE_USERNAME
    - secure: "FVPsapeM3HaYhvILV2ZEz3FTj5ABRANkpzCs7t6t4ZyNUoAG67Rl6GEbOvMRB5mNeLi8fxG+Sxyd0fza9WF7gwkJxY2WkMJNXXUkuwOuaP39fgIIKC5fVCgmf7tSuJYox82DdKyi3KSLw+2ToS382h70ZgAwHgS4hk0pI7O/hA4="
    # SONATYPE_PASSWORD
    - secure: "XXXgkc5bD6oz5HRbkxZbA8WXz+o/oK5aOeU/jUTMOLeszJOeDlQtPWUbGu16kC8U6OeAxI5u3a/tz6r6h7dPx45A+kNBKBh5WE6domw7ab0UXADagZIrf336ren0vIAhvWxeAipE/YSBQpgn4rNG+ppSAowKTnlL0Sg+D5Lnyx8="
    # BINTRAY_USER
    - secure: "UMB7QXXN0PWHf/cyfpnBGDCou0cojU/a03dtuXX0Bb+Ijyq4R2GtAY9kX8H+bLZx16CX5J7ZNVallx87aLuHB95XmigDeOhEP+RYaI7P81O9tKpgrhbSg7rn9jBEQsQuns73EF7kMgUdbCZQ0OxYheVMQ8U+MR7U37vHtySmUwQ="
    # BINTRAY_API_KEY
    - secure: "hitcVHPfo0ztYCLQY0fkVZuZWb6z5uhi/zdSesQBZLBI2LE4nU85pbZqkde1faA4EMYHpRHsazJ+Ec7KhOuTGJGpbEvMYzjUvxSPXjTqag8e6P4KHaEWAXFg9dfNuiPIOUVDs+xOZMQ00pNKAtEFbJ0frpkoj5FBWHMEWmR3XIA="
    # CODACY_PROJECT_TOKEN (https://github.com/codacy/codacy-coverage-reporter#setup)
    - secure: "lZxQdwYe2PmyjZAmG7K6XUD6IX6HNgCrVGmvOOhr7Yk/KmqyvnICX9NwTI6ImT2QL+NeoM+ZDVecAhyRXKvtaTcyJap1cUxung778cMzoEfjXCtHAqVXZsfTNdPApmAzkECQO5zpRas0WNs4oqBtOTHTyE58eP04+tBp7AqqpVU="
matrix:
  # A build will finish as soon as a job has failed, rather than running the
  # remaining jobs and accumulating failures.
  fast_finish: true
before_install:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
after_success:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - ./gradlew coveralls
  - ./gradlew versionEyeSecurityCheck
  - ./gradlew versionEyeLicenseCheck
  - ./gradlew versionEyeUpdate
  - ./gradlew artifactoryPublish
  - ./gradlew bintrayUpload
after_failure:
  - ./gradlew clean check --debug
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0cb3de5ece8a0c503bca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
addons:
  coverity_scan:
    project:
      name: "universal-automata/liblevenshtein-java"
      #description: "Build submitted via Travis CI"
    notification_email: dylon.devo+github@gmail.com
    build_command_prepend: ""
    build_command:   "./gradlew clean build"
    #branch_pattern: coverity_scan
    branch_pattern: master
