language: java
jdk:
  - oraclejdk8
after_success:
  - ./gradlew check jacocoTestReport coveralls
after_failure:
  - ./gradlew clean check --debug
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0cb3de5ece8a0c503bca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "In3/FzSdMz+o5Tqho05dXGFeqeb/XWo0D0rdhKZ5acp6D/lxjTw8Xo/tMZQb9Ur50XDMn4SdjyGnfkiYRar13g51+xlOnY+4MUqtRzvfuLyohtOMN8PrmQbNWVneuq3I/Xn+fcDWsZavqmUGB7hac5h6Uip4qq8YnbFy5Gn6v6I="
addons:
  coverity_scan:
    project:
      name: "universal-automata/liblevenshtein-java"
      description: "Build submitted via Travis CI"
    notification_email: dylon.devo+github@gmail.com
    build_command_prepend: ""
    build_command:   "./gradlew build"
    #branch_pattern: coverity_scan
    branch_pattern: master
#script:
  #- ./gradlew build
