language: java
jdk:
  - oraclejdk8
after_success:
  - ./gradlew check jacocoTestReport coveralls
after_failure:
  - ./gradlew clean check --debug
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0cb3de5ece8a0c503bca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
